language: cpp
sudo: false

script:
  #############################################################################
  # Disallow PRs to `ComputationalRadiationPhysics/picongpu` branch `master`  #
  # if not an other mainline branch such as `dev` or `release-...`            #
  #############################################################################
  - . test/correctBranchPR

  #############################################################################
  # Conformance with Alpaka: Do not write __global__ CUDA kernels directly    #
  #############################################################################
  - test/hasCudaGlobalKeyword include/pmacc
  - test/hasCudaGlobalKeyword share/pmacc/examples
  - test/hasCudaGlobalKeyword include/picongpu
  - test/hasCudaGlobalKeyword share/picongpu/examples

  #############################################################################
  # Disallow end-of-line (EOL) white spaces                                   #
  #############################################################################
  - test/hasEOLwhiteSpace

  #############################################################################
  # Disallow TABs, use white spaces                                           #
  #############################################################################
  - test/hasTabs

  #############################################################################
  # Disallow non-ASCII in source files and scripts                            #
  #############################################################################
  - test/hasNonASCII

  #############################################################################
  # Disallow spaces before pre-compiler macros                                #
  #############################################################################
  - test/hasSpaceBeforePrecompiler
