#!/usr/bin/env bash
#
# Copyright 2013-2020 Axel Huebl, Rene Widera, Richard Pausch
#
# This file is part of PIConGPU.
#
# PIConGPU is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PIConGPU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PIConGPU.
# If not, see <http://www.gnu.org/licenses/>.
#

#
# generic compile options
#

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps


flags[0]="-DPARAM_OVERWRITES:LIST='-DPARAM_LASERPROFILE=PlaneWave;-DPARAM_A0=20;-DPARAM_PULSELENGTH=3e-14;-DPARAM_PULSEINIT=9.0;-DPARAM_TARGETDENS=200;-DPARAM_TARGETSIZE=0.25;-DPARAM_TARGETPOS=10;-DPARAM_TARGETPOSX=8.0;-DPARAM_TARGETSCALELENGTHREAR=0.0;-DPARAM_TARGETSCALELENGTHFRONT=0.0;-DPARAM_KSTRIPES=3.142;-DPARAM_AMPSTRIPES=0;-DPARAM_KRIPPLES=3.142;-DPARAM_AMPRIPPLES=0;-DPARAM_RIPPLESTHICKNESS=0.1;-DPARAM_XANTEIL=0;-DPARAM_RES=192;-DPARAM_PPC=64u;-DPARAM_PSHAPE=TSC'"


################################################################################
# execution

case "$1" in
    -l)  echo ${#flags[@]}
         ;;
    -ll) for f in "${flags[@]}"; do echo $f; done
         ;;
    *)   echo -n ${flags[$1]}
         ;;
esac
