#!/usr/bin/env bash
#
# Copyright 2013-2017 Axel Huebl, Rene Widera
#
# This file is part of PIConGPU.
#
# PIConGPU is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PIConGPU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PIConGPU.
# If not, see <http://www.gnu.org/licenses/>.
#

#
# generic compile options
#

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

flags[0]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=Esirkepov<UsedParticleShape>;-DPARAM_PARTICLESHAPE=CIC;-DPARAM_DIMENSION=DIM3"
flags[1]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=Esirkepov<UsedParticleShape>;-DPARAM_PARTICLESHAPE=TSC;-DPARAM_DIMENSION=DIM3"
flags[2]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=Esirkepov<UsedParticleShape>;-DPARAM_PARTICLESHAPE=PCS;-DPARAM_DIMENSION=DIM3"
flags[3]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=Esirkepov<UsedParticleShape>;-DPARAM_PARTICLESHAPE=P4S;-DPARAM_DIMENSION=DIM3"
flags[4]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=Esirkepov<UsedParticleShape>;-DPARAM_PARTICLESHAPE=CIC;-DPARAM_DIMENSION=DIM2"
flags[5]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=Esirkepov<UsedParticleShape>;-DPARAM_PARTICLESHAPE=TSC;-DPARAM_DIMENSION=DIM2"
flags[6]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=Esirkepov<UsedParticleShape>;-DPARAM_PARTICLESHAPE=PCS;-DPARAM_DIMENSION=DIM2"
flags[7]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=Esirkepov<UsedParticleShape>;-DPARAM_PARTICLESHAPE=P4S;-DPARAM_DIMENSION=DIM2"
flags[8]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=EmZ<UsedParticleShape>;-DPARAM_PARTICLESHAPE=CIC;-DPARAM_DIMENSION=DIM3"
flags[9]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=EmZ<UsedParticleShape>;-DPARAM_PARTICLESHAPE=TSC;-DPARAM_DIMENSION=DIM3"
flags[10]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=EmZ<UsedParticleShape>;-DPARAM_PARTICLESHAPE=PCS;-DPARAM_DIMENSION=DIM3"
flags[11]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=EmZ<UsedParticleShape>;-DPARAM_PARTICLESHAPE=P4S;-DPARAM_DIMENSION=DIM3"
flags[12]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=EmZ<UsedParticleShape>;-DPARAM_PARTICLESHAPE=CIC;-DPARAM_DIMENSION=DIM2"
flags[13]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=EmZ<UsedParticleShape>;-DPARAM_PARTICLESHAPE=TSC;-DPARAM_DIMENSION=DIM2"
flags[14]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=EmZ<UsedParticleShape>;-DPARAM_PARTICLESHAPE=PCS;-DPARAM_DIMENSION=DIM2"
flags[15]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=EmZ<UsedParticleShape>;-DPARAM_PARTICLESHAPE=P4S;-DPARAM_DIMENSION=DIM2"
flags[16]="-DCUDA_ARCH=37 -DPARAM_OVERWRITES:LIST=-DPARAM_CURRENTSOLVER=VillaBune<>;-DPARAM_PARTICLESHAPE=CIC;-DPARAM_DIMENSION=DIM3"


################################################################################
# execution

case "$1" in
    -l)  echo ${#flags[@]}
         ;;
    -ll) for f in "${flags[@]}"; do echo $f; done
         ;;
    *)   echo -n ${flags[$1]}
         ;;
esac
