#!/usr/bin/env bash
#
# Copyright 2013-2019 Axel Huebl, Rene Widera, Richard Pausch
#
# This file is part of PIConGPU.
#
# PIConGPU is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PIConGPU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PIConGPU.
# If not, see <http://www.gnu.org/licenses/>.
#

#
# generic compile options
#

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

flags[0]="-DPARAM_OVERWRITES:LIST='-DPARAM_PPC=40u;-DSIMDIM=DIM2'"
flags[1]="-DPARAM_OVERWRITES:LIST='-DPARAM_PPC=20u'"
flags[2]="-DPARAM_OVERWRITES:LIST='-DPARAM_PPC=10u'"
flags[3]="-DPARAM_OVERWRITES:LIST='-DPARAM_PPC=1u'"
flags[4]="-DPARAM_OVERWRITES:LIST='-DPARAM_PPC=40u;-DSIMDIM=DIM2' -DCMAKE_CUDA_FLAGS='-g -G -cudart shared' -DCMAKE_CXX_FLAGS='-g -O0' -DCMAKE_C_FLAGS='-g -O0' -DPIC_USE_ISAAC=OFF -DPIC_USE_PNGwriter=OFF -DPIC_USE_openPMD=OFF -DPMACC_BLOCKING_KERNEL=ON"

#flags[5]="-DPARAM_OVERWRITES:LIST='-DPARAM_PPC=8u;-DPARAM_RESOLUTION=24.0'"


################################################################################
# execution

case "$1" in
    -l)  echo ${#flags[@]}
         ;;
    -ll) for f in "${flags[@]}"; do echo $f; done
         ;;
    *)   echo -n ${flags[$1]}
         ;;
esac
